### ISSUE TITLE
support for reading aws credentials & config file from environment variables...

### ISSUE THREAD

**Issue by tekdj7** [victorskl/yawsso#18]
Read Environment Variables below to determine where to check for aws credentials and config.  I have folders that each have their own aws credentials/config files for said AW accounts.  My sso cache is still located in default location: ~/.aws/sso

AWS_SHARED_CREDENTIALS_FILE
AWS_CONFIG_FILE

See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by victorskl** [comment]
Right! This is doable, accepted.

**Comment by victorskl** [comment]
Come with PR https://github.com/victorskl/yawsso/pull/21 
User test available with `pip install -U yawsso==0.5.0rc1`

**Comment by victorskl** [comment]
Closed with #23 and GA now with `pip install -U yawsso==0.5.0`
