### ISSUE TITLE
sync all profiles matching a pattern, such as lab*

### ISSUE THREAD

**Issue by tekdj7** [victorskl/yawsso#20]
sync all profiles matching a pattern, such as lab*

**Comment by victorskl** [comment]
Just to make sure I understood it right. Is that mean: 

- **When**: you `yawsso -p lab*` 
- **Expect**: all named profiles start with `lab` will be updated?

Otherwise, can you elaborate a bit more on your user story in similar points form, please.

**Comment by tekdj7** [comment]
yes, you understood correctly.

**Comment by victorskl** [comment]
Come with PR https://github.com/victorskl/yawsso/pull/22 
User test available with `pip install -U yawsso==0.5.0rc1`

**Comment by victorskl** [comment]
Closed with #23 and GA now with `pip install -U yawsso==0.5.0`
