### ISSUE TITLE
Either create AWS_SHARED_CREDENTIALS_FILE, or make it more clear it just needs to be created if it doesn't exist yet

### ISSUE THREAD

**Issue by Snapstromegon** [victorskl/yawsso#26]
I had no version of AWS CLI v1 running on my system ever, so yawsso failed on me by saying ".../.aws/crendetials does not exist".

As a user I did not know that the credentials file just needed to exist as an empty file for the script to work. I had expected, that the tool would "just create" the file if it didn't exist yet.

Maybe the behavior can be changed, or the output could contain something like "please create this as an empty file if you want to use this path". That way a user wouldn't start a search for his/her error.

**Comment by victorskl** [comment]
Yap of course. Thanks for feedback; will fix!
