### ISSUE TITLE
Improve subcommand and args handling

### ISSUE THREAD

**Issue by victorskl** [victorskl/yawsso#30]
Python built-in `argparse` does work well for simple CLI args parsing. But it does not cover well for sub-commands,  global/sub-level args help options and growing CLI App use cases.

- CLI args and help option become a bit convoluted, see [L353](https://github.com/victorskl/yawsso/blob/75000b1eb7a7dc84ced88a318ef07152d8b024ea/yawsso/cli.py#L353)
- App logic started needing a bit of dance around it, see [L394](https://github.com/victorskl/yawsso/blob/75000b1eb7a7dc84ced88a318ef07152d8b024ea/yawsso/cli.py#L394)
- Introduce unnecessary bug, see https://github.com/victorskl/yawsso/issues/24

Potential solution is refactored to adapt [Click](https://click.palletsprojects.com/en/7.x/why/) or [docopt](https://github.com/docopt/docopt). ... will be trying with Click, first.

**Comment by brainstorm** [comment]
My personal go-to reference when refactoring CLIs in python w/ Click: https://github.com/ewels/MultiQC/blob/master/multiqc/multiqc.py ;)

**Comment by victorskl** [comment]
On the second thought, still like the fact that `yawsso` has no major dependencies but just with Python standard lib... I will shelf this refactor for now and revisit later. Thanks for pointer and given it thought!
