### ISSUE TITLE
ValueError on time data again

### ISSUE THREAD

**Issue by bilsch** [victorskl/yawsso#48]
```
❯ pip list | grep yawsso
yawsso              0.6.2
❯ aws --version
aws-cli/2.2.5 Python/3.9.5 Darwin/19.6.0 source/x86_64 prompt/off
```

`ValueError: time data '2021-05-25T23:20:06Z' does not match format '%Y-%m-%dT%H:%M:%SUTC'`

If I manually hack the json file ( fgrep -lr that timestamp in ~/.aws ) to match what the error is giving and yawsso works just fine.

**Comment by kieranharrigan** [comment]
@bilsch I would double check that the version of `yawsso` you're invoking is actually `0.6.2`, e.g. I would run `yawsso --version`. The error you're receiving seems to imply that you're running an older version of `yawsso` that did not yet account for the change in expiry time format, such as version `0.6.0`. Relevant PR: https://github.com/victorskl/yawsso/pull/44/files

**Comment by bilsch** [comment]
ah interesting good catch - yea when I run the command its 0.5.0 so I must have some kind of odd path / shell thing.

Thanks for the quick response!

**Comment by bilsch** [comment]
yea somehow bash had 0.5.0 - hash -r fixed it!
