### ISSUE TITLE
yawsso -e only exports Linux form of environment variables

### ISSUE THREAD

**Issue by eschulma** [victorskl/yawsso#57]
In most cases yawsso works extremely well for both Linux and Windows. There is one exception: the command `yawsso -e` prefaces each variable with "export " while Windows uses "set ".  It would be great to have an option for Windows development as well. Maybe -ew as the option?

Thank you for writing such a great tool.

**Comment by victorskl** [comment]
It comes with since `1.0.0rc2`. User test avail with `pip install -U yawsso==1.0.0rc2`
