### ISSUE TITLE
Automatically log in when sync fails

### ISSUE THREAD

**Issue by remmelt** [victorskl/yawsso#60]
Hello and thanks for this useful tool!

Our use case is like this: 

```
yawsso --profile x

# if exit code != 0
yawsso --login --profile x
```

It would be awesome if this could be a single command, doing a sync if possible, and doing login only if necessary. 

How does this sound to you?

**Comment by victorskl** [comment]
Ah, right! Can't promise but I can explore the use case. If there is not much implication to existing use cases then it should do, yes. :)

**Comment by remmelt** [comment]
It would be way nicer than my bash script 😄

**Comment by victorskl** [comment]
This is avail as of rc3 under `auto` subcommand. `pip install -U yawsso==1.0.0rc3`

Usage:
https://github.com/victorskl/yawsso/blob/main/README.md#auto-login-then-sync
