### ISSUE TITLE
syncing for all named profiles fails when cache for first profile is not active on first time set up

### ISSUE THREAD

**Issue by es50678** [victorskl/yawsso#66]
Hello,

> Summary
When I try to sync all named profiles with `yawsso`, it fails unless the first profile in `config` is cached.

> yawsso version
yawsso 0.7.2

> aws-cli version
aws-cli/2.7.11 Python/3.10.5 Darwin/21.5.0 source/arm64 prompt/off

> system
![image](https://user-images.githubusercontent.com/17823824/176946838-42008371-686a-426e-93d8-6a952e579f0c.png)

## On first time use...

I have 4 sso profiles in my config:
```
[profile prodDeveloper]
...
[profile prodQABuilder]
...
[profile prodLeadDeveloper]
...
[profile prodAdmin]
...
```

I have `prodAdmin` cached, but nothing else and try to run `yawsso`
```
❯ yawsso
Current cached SSO login is expired since 2022-06-30T04:53:01-04:00. Try login again.

❯ export AWS_PROFILE=prodAdmin

❯ aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:
....
Successfully logged into Start URL: https://d-92677f5210.awsapps.com/start#/

❯ yawsso
Current cached SSO login is expired since 2022-06-30T04:53:01-04:00. Try login again.
```

I then login for `prodDeveloper` and everything works
```
❯ export AWS_PROFILE=prodDeveloper

❯ aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:
....
Successfully logged into Start URL: https://staxlabs.awsapps.com/start#/

❯ yawsso
SUCCESS
```

I'm not sure if this is also a problem after the first time use, but I wanted to document it while I could.

I'll also try to take a look into the code base, i want more experience with python and hopefully I can hack it out.

**Comment by victorskl** [comment]
Hey thanks for reporting. I think I get a glimpse about procedural issue there. But. let me try to reproduce and confirm. Yah feel free to look around the code, there. 🙂

**Comment by victorskl** [comment]
Thanks for forensic. 

Right! 2 SSO cache files from 2 SSO sessions. I will see if I can reproduce that -- might be handy to see your `~/.aws/config` profiles counterpart on SSO setup there. If you can share, pls kindly REDACTED/mock them. I only need to know general config structure in there. 

If you think `yawsso` is still producing the correct behaviour, we can close the issue, yes. We could drop a note in Wiki tab -- so that it helps next user who might encounter.
