### ISSUE TITLE
Not able to sync all profiles

### ISSUE THREAD

**Issue by PrajIT3007** [victorskl/yawsso#7]
Hi,

I am currently trying yawsso. I have multiple profiles setup in my config file.
As describe in the doc: running yawsso should sync all profiles in my credentials file, but I have only the default profile which is synced. 

When specifying the profile via the option -p it is working.

**Comment by victorskl** [comment]
Thanks. It will come with release `0.3.0` in this https://github.com/victorskl/yawsso/pull/8

**Comment by victorskl** [comment]
Release `0.3.0` is [available in PyPI](https://pypi.org/project/yawsso/0.3.0/) now. If you have previous installation, please upgrade it as `pip install -U yawsso`. Please refer updated README for how to.
