### ISSUE TITLE
Request: do not put region into the profile written to ~/.aws/credentials

### ISSUE THREAD

**Issue by et304383** [victorskl/yawsso#76]
I am not using any given region by default, and do not want the following in my profiles after calling yawsso:

```
region = us-east-1
```

Please provide support for not writing this value, as right now I have to sed afterwards to delete these lines.

**Comment by victorskl** [comment]
Okay! I will need to investigate this a bit. I got feedback about this `region` flag from elsewhere, too. I will dig AWS doc again to understand better.

**Comment by victorskl** [comment]
Ok; I don't find any doc evidence that `region` must exist in `~/.aws/credentials`. So. I will be removing it, yes. 🙂

**Comment by victorskl** [comment]
This is now avail for public review with `rc2`.

https://pypi.org/project/yawsso/1.1.0rc2/

```
pip install -U yawsso==1.1.0rc2
```

I will test it myself a bit; these days. If all good, it will come GA when closing [1.1.0 milestone](https://github.com/victorskl/yawsso/milestone/8).

**Comment by victorskl** [comment]
This is now released and GA. https://github.com/victorskl/yawsso/releases/tag/1.1.0

```
pip install -U yawsso==1.1.0
```
