### ISSUE TITLE
New Windows -e process is too restrictive

### ISSUE THREAD

**Issue by sebekz** [victorskl/yawsso#77]
The change implemented in https://github.com/victorskl/yawsso/pull/69 makes an assumption, that if you are in Windows, you don't use bash or the `export` syntax. 

While it may be correct in some situations, there are Windows environments where bash is being used. It's not a huge deal to transform the PowerShell-compatible output into a bash-compatible one, but it would be great if there was a cli flag that could just say - use a specific style of export temporary variables.

**Comment by victorskl** [comment]
Ah. Right. Okay, understood what you are saying there. I will see how I can improve this UX, a bit with next release.

**Comment by victorskl** [comment]
This is now avail for public review with `rc2`.

https://pypi.org/project/yawsso/1.1.0rc2/

```
pip install -U yawsso==1.1.0rc2
```

I will test it myself a bit; these days. If all good, it will come GA when closing [1.1.0 milestone](https://github.com/victorskl/yawsso/milestone/8).

**Comment by victorskl** [comment]
This is now released and GA. https://github.com/victorskl/yawsso/releases/tag/1.1.0

```
pip install -U yawsso==1.1.0
```
