### ISSUE TITLE
can't get aws credentials in cmd line

### ISSUE THREAD

**Issue by KetakiSharma** [victorskl/yawsso#78]
$ yawsso login --profile profile-name  -e
$Rai:NJF_NPPRFF_XRL_VQ="**************"
$Rai:NJF_FRPERG_NPPRFF_XRL="*****************"
$Rai:NJF_FRFFVBA_GBXRA="***********************"

I don't understand why it's not providing AWS_ACCESS_KEY which it used to; this is the same output regardless of powershell or gitbash. However, credentials are generated and can see in .aws/credentials file and they do work but not able to see on cmd line.

I have tried uninstalling and installing back. 
I am running yawsso 1.0.1 the version 

could someone please help.

Many thanks

**Comment by victorskl** [comment]
Ah. Since v1 onwards, you will need to decrypt the exported token.

```
echo 'Rai:NJF_NPPRFF_XRL_VQ=""' | yawsso decrypt
Env:AWS_ACCESS_KEY_ID=""
```

Then. Like so.

```
yawsso login --profile profile-name -e | yawsso decrypt
```

I reckon, pipe commands should work in PowerShell!

**Comment by KetakiSharma** [comment]
Thank you. It works now.
