### ISSUE TITLE
yawsso auto without cache

### ISSUE THREAD

**Issue by linuxkd** [victorskl/yawsso#87]
When running `yawsso auto` if there is a previous AWS SSO cache, it will properly cause the login function to execute and renew the credentials. If there is no cache present, `yawsso auto` fails with the following error:
> Can not find valid AWS CLI v2 SSO login cache in /user/profile/.aws/sso/cache for profile profile-name.

The AWS cache is removed automatically by homebrew updates of the awscli formula. 

I suggest that if the cache is empty, but there is valid configuration for SSO, that `yawsso auto` calls `aws sso login` or similar, and then performs any needed actions to generate the v1 creds afterward.

**Comment by victorskl** [comment]
Um. Hear you! Agree that `yawsso auto` sub command flow is not robust there yet. Thanks for sharing your use case and suggesting. I will find sometime to explore.

**Comment by linuxkd** [comment]
> Um. Hear you! Agree that `yawsso auto` sub command flow is not robust there yet. Thanks for sharing your use case and suggesting. I will find sometime to explore.

Thanks so much. If it would be helpful, I could attempt to implement the change as described if that is something you would be open to. I don't like to spend the time without knowing ahead of time if it would be welcome.

**Comment by victorskl** [comment]
Oh, Sure. PR always welcome, of course, pls.

**Comment by victorskl** [comment]
Sorry for the year long wait. The yawsso-1.2.0 out.!

```
pip install -U yawsso==1.2.0
```

This should work now..

- Clear away all sso caches
```
rm -rf ~/.aws/sso/cache/*.json
```

- Then, try like so:
```
yawsso auto --profile dev
```
