### ISSUE TITLE
Add parameter to control setting the region in the .aws/credentials file

### ISSUE THREAD

**Issue by David-HH-Dev** [victorskl/yawsso#88]
Hi @victorskl,

I came across the issue reported in https://github.com/victorskl/yawsso/issues/76 because I was wondering why the aws clients are telling me that there is no default region defined in the profile. It has been working before, but then since I updated yawsso I started to have an issue. So actually my request would be the opposite as what is explained in https://github.com/victorskl/yawsso/issues/76. Do you think it would be possible to implement a parameter so that you can define whether you want the region in the credentials file or not? Something like a switch "-r" to tell it to copy the region for example?
yawsso -p dev:foo -r

**Comment by victorskl** [comment]
Okay. Let me see to this.

**Comment by victorskl** [comment]
The yawsso-1.2.0 out.!

```
pip install -U yawsso==1.2.0
```

```
```
