### ISSUE TITLE
How can I skip encrypt?

### ISSUE THREAD

**Issue by zhaoyi0113** [victorskl/yawsso#91]
Is there a way to skip encryption when run `yawsso -p xxx`

**Comment by victorskl** [comment]
Encrypt (substitution cypher) is yawsso feature. ditto [note](https://github.com/victorskl/yawsso/wiki#release-100-notes)

**Comment by victorskl** [comment]
If you want none encrypted cred export into the current shell, you can now directly use aws cli. It comes with this pull https://github.com/aws/aws-cli/pull/7398

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/export-credentials.html

```
aws configure export-credentials --profile dev --format env | source /dev/stdin
```
